### ISSUE TITLE
Parsing failure with exec_manualquery

### ISSUE THREAD

**Issue by AndrewIrwin** [simonscmap/cmap4r#1]
I ran into a query problem where missing data causes the tidyverse tibble functions (read_csv? I forget the details) to guess a column is “logical” rather than “double”. The read_csv function allows you to override the column specification. Perhaps something like this would be useful for exec_manualquery?
 
Here’s some code illustrating the problem a the idea for the fix:
 
This works fine:
  mq = "select * from tblSeaFlow where cruise in ( 'KM1513', 'KM1606', 'MGL1704', 'KM1906')"
  seaflow = exec_manualquery(mq)
 
(A file used below can be created using
  seaflow %>% filter(cruise != "KM1513") -> seaflow
  write_csv(seaflow, "seaflow-many-cruise-2019-12-03.csv")
)
 
This fails:
  mq = "select * from tblSeaFlow where cruise in ( 'KM1606', 'MGL1704', 'KM1906')"
  seaflow = exec_manualquery(mq)
 
If the data from the second query (correctly parsed) is saved to a csv file, then the following fails,
  seaflow <- read_csv("seaflow-many-cruise-2019-12-03.csv")
But this read_csv works
  seaflow <- read_csv("seaflow-many-cruise-2019-12-03.csv", col_types ="Tddcddddddddddddddddddddd")
 
Andrew

**Comment by amishra-stats** [comment]
Thank you for your suggestion, Andrew.  We have recognized the problem. In the updated version of the package, the issue has been resolved.
