### ISSUE TITLE
Variable names keep changing

### ISSUE THREAD

**Issue by sangwon-hyun** [simonscmap/cmap4r#10]
Not a major issue, but when table and/or variable names in CMAP change, code in our scripts for our bookdown documentation don't run properly anymore. For instance, in the `tblSeaFlow` table, the species abundances changed from `'synecho_abundance'` to `'abundance_synecho'`. This broke our colocalization example.

(One clean solution would be for CMAP to have some sort of version control ability.)

**Comment by sangwon-hyun** [comment]
Another possible solution is for one of us to do a periodic (monthly, automatic) updated check of all the variable names and tables that we use, simply to see if anything has changed. If anything is off, then one of the maintainers can manually update and check.

Something like a unix `cron` job on my computer that runs a script, to be run on the first day of every month, might work. If we want to use a solution, this sort of thing is promising: 
https://jasonet.co/posts/scheduled-actions/ 

A better solution, would be to set up a notification mechanism (from the client side, or from the CMAP side) if any major changes occur in CMAP. 

And of course, the cleanest solution would still be some sort of CMAP version control.

**Comment by jacobbien** [comment]
Perhaps the best would be a cron job (running once a month) that tries to
regenerate the bookdown and checks if there were errors.  The advantage is
that this would guard against any CMAP changes that would affect us, not
just changing variable names.

**Comment by sangwon-hyun** [comment]
@amishra-stats I did this by adding a shell script to the `bookdown/.` directory, and using _crontab_ (automatic scheduling of jobs on unix) to run it twice a week! You can do the same, by `crontab -e` on command line, then adding the line 
```0 12 1,14 * * /home/sangwonh/repos/cmap4r/bookdown/bookdown-monthly-diff.sh```
The file `bookdown-monthly-diff.sh` looks like [this](https://github.com/simonscmap/cmap4r/blob/master/bookdown/bookdown-monthly-diff.sh)
```
#!/bin/bash

Rscript -e "library(cmap4r); initialize_cmap(cmap_key='your_key_goes_here'); bookdown::render_book('.')"

echo "==================================" >> bookdown-monthly-diff.txt
echo "Difference in bookdown for this month:" >> bookdown-monthly-diff.txt
echo $(date) >> bookdown-monthly-diff.txt
git diff . >> bookdown-monthly-diff.txt
echo "==================================" >> bookdown-monthly-diff.txt

# sendmail robohyun66@gmail.com < bookdown-monthly-diff.txt
mail -s 'Monthly cmap4r bookdown diff' robohyun66@gmail.com < bookdown-monthly-diff.txt
```
Pretty neat, right? I'm closing this issue now.
