### ISSUE TITLE
User-reported error about `get_spacetime()`

### ISSUE THREAD

**Issue by sangwon-hyun** [simonscmap/cmap4r#11]
Hi all! I just ran into an error while trying to access tblMGL1704_Gradients2_Nutrients using get_spacetime. Received the following:
Warning: 15 parsing failures.
row     col expected    actual         file
  2 Station a double Underway2 <raw vector>
  3 Station a double Underway3 <raw vector>
  4 Station a double Underway4 <raw vector>
  5 Station a double Underway5 <raw vector>
  7 Station a double Underway6 <raw vector>
... ....... ........ ......... ............
See problems(...) for more details.
I guess because of the mixed numeric/string data in the station column. I downloaded the data manually, but just thought I'd flag this.

**Comment by tmholmes** [comment]
Here is the code I ran to receive error (same code worked with CTD, trace metal and Chla datasets):
```
#load libraries
library(cmap4r)
library(dplyr)
library(ggplot2)

set_authorization(cmap_key = "xxx")

#get gradients 2 data
cruisename = "MGL1704"
Gradients2metadata <- get_cruise_by_name(cruisename)

#Macro nutrient data  for upper 20m
dt1 = as.character(Gradients2metadata[['Start_Time']])
dt2 = as.character(Gradients2metadata[['End_Time']])
Gradients2Nuts <- get_spacetime(tableName = 'tblMGL1704_Gradients2_Nutrients',
                                varName = '*',
                                dt1,
                                dt2,
                                lat1 = Gradients2metadata[['Lat_Min']],
                                lat2 = Gradients2metadata[['Lat_Max']],
                                lon1 = Gradients2metadata[['Lon_Min']],
                                lon2 = Gradients2metadata[['Lon_Max']],
                                depth1 = 0,
                                depth2 = 20)
```

**Comment by sangwon-hyun** [comment]
OK as far as I can tell, this warning is harmless! It's just when `readr::read_csv()` parses the result of an SQL query, it issues warnings if there are NAs, which is expected. I've suppressed this warning.

```Browse[2]> + > readr::read_csv(response$content, 
+                     col_types = paste0(ctype, collapse = ''))
Warning: 15 parsing failures.
row     col expected    actual         file
  2 Station a double Underway2 <raw vector>
  3 Station a double Underway3 <raw vector>
  4 Station a double Underway4 <raw vector>
  5 Station a double Underway5 <raw vector>
  7 Station a double Underway6 <raw vector>
... ....... ........ ......... ............
See problems(...) for more details.

# A tibble: 30 x 15
   time                  lat   lon depth Station  Cast RosPos  SiO4 NO3_NO2    TN   TON    PO4    TP   TOP   TOC
   <dttm>              <dbl> <dbl> <dbl>   <dbl> <dbl>  <dbl> <dbl>   <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>
 1 2017-05-30 13:28:39  28.5 -158.  15.1       3     1      5  2.28 0.003    4.66  4.66 0.0321 0.207 0.175  69.7
 2 2017-05-30 16:00:00  30.3 -158    7        NA    NA     NA  2.45 0.0101   4.59  4.58 0.0320 0.200 0.168  72.5
 3 2017-05-30 20:00:00  31.0 -158    7        NA    NA     NA  3.04 0.00664  4.71  4.70 0.0401 0.219 0.178  68.8
 4 2017-05-31 04:39:00  32.3 -158    7        NA    NA     NA  3.55 0.00287  4.61  4.61 0.0489 0.209 0.160  67.1
 5 2017-05-31 09:29:00  33.0 -158    7        NA    NA     NA  3.97 0.00263  4.44  4.43 0.0693 0.213 0.144  64.4
 6 2017-05-31 13:37:55  32.3 -158.  14.9       4     1     10  3.60 0.003    4.45  4.44 0.0508 0.201 0.150  63.7
 7 2017-05-31 15:25:00  33.7 -158    7        NA    NA     NA  4.56 0.00349  4.69  4.68 0.0914 0.234 0.143  66.5
 8 2017-05-31 17:26:00  34.4 -158    7        NA    NA     NA  4.21 0.00436  4.37  4.37 0.0851 0.230 0.145  63.7
 9 2017-05-31 21:55:00  35.2 -158    7        NA    NA     NA  4.11 0.00440  4.69  4.68 0.108  0.255 0.147  62.9
10 2017-06-01 08:39:00  36.6 -158    7        NA    NA     NA  4.58 0.00824  4.74  4.73 0.0999 0.272 0.172  63.1
# … with 20 more rows
```

**Comment by tmholmes** [comment]
Thank you Sangwon! However, I don't think this issue is quite resolved yet, because if you check the dataset, you'll see that the NAs under 'Station' should be station names, but they are strings. Therefor the dataset downloaded through R is missing vital information. Perhaps if the numeric cells under 'Station' were also encoded as strings this issue wouldn't occur? Very sorry I didn't even check the tibble after I received the errors... rookie mistake!

**Comment by amishra-stats** [comment]
Hi Tom
Thanks for pointing out the issue!
We checked the variable description using get_catalog() function. 
Apparently, station information is stored as station number (#) in the original data on the Simons CMAP data base. Hence, our function is extracting the data accordingly. 

tableName <- "tblMGL1704_Gradients2_Nutrients"
temp <- get_catalog()
View(temp[temp$Table_Name == tableName, ])

**Comment by amishra-stats** [comment]
Also,  NA value in some cases simply suggest that the data is not available.

**Comment by tmholmes** [comment]
Thanks for looking into this. When I download the data as csv directly from the CMAP website, the first 5 elements in the 'Station' variable are: 3; Underway2; Underway3; Underway4; Underway5; 4. When downloading the data through cmap4r, the first 5 elements in the 'Station' variable are: 3; NA; NA; NA; NA; 4. It is obvious that this is because the variable is recognised as numeric and not string. There is data there, it is just not being recognised correctly.

**Comment by amishra-stats** [comment]
Thanks!
To streamline the download of data, our function depend on the data catalog description provided by the authors. We will request Simons CMAP data base group to declare the variable as "string" as they do it in other cases. I hope this will sort out the issue. 

You can clearly see that they are describing the variable as number.

tableName <- "tblMGL1704_Gradients2_Nutrients"
temp <- get_catalog()
View(temp[temp$Table_Name == tableName, ])

1 | Station | tblMGL1704_Gradients2_Nutrients | Station Number | #

**Comment by tmholmes** [comment]
Excellent. Had I known that there was a CMAP database group responsible for allocating variables to data types I would have asked them directly, instead of annoying you =) Thanks!
