### ISSUE TITLE
along_track(): Unable to use scalar tolerances

### ISSUE THREAD

**Issue by ANetTow** [simonscmap/cmap4r#15]
When setting the tolerance parameters in along_track() to a single value, I get an error stating "Error in request(payload, route, apiKey) :  check_error(response) is not TRUE."

When setting the tolerance parameters to vectors the same length as targetVars, the function works as expected.

**Comment by sangwon-hyun** [comment]
Thanks for the report! Just to be clear, you would like to provide a single  number for each of the tolerance values when you're doing queries for multiple tables & variables (which makes sense, but just checking)?

**Comment by ANetTow** [comment]
That’s correct! The same tolerance for all variables.

Annette

**Comment by sangwon-hyun** [comment]
Fixed https://github.com/simonscmap/cmap4r/commit/0b1beee74c2a19e11b37645539700c2d0febb86a !  And you were right in the first place, that's what the documentation says -- that you can provide a single tolerance value if you want.
