### ISSUE TITLE
CMAP API Key isn't persistent across R sessions

### ISSUE THREAD

**Issue by sangwon-hyun** [simonscmap/cmap4r#5]
I'd like to not have to enter the API key for every new R session. For instance, whenever I open an new R session and try something simple like: 

"library(cmap4r)
bounds = get_cruise_bounds("MGL1704")"

I am prompted to enter the API Key every time

**Comment by robohyun66** [comment]
I kind of went down a rabbit hole investigating this too much. It seems that in Linux, the keyring backend is not properly running. Some leads:

1. The warning message here is informative:
_warning("Selecting ", sQuote("env"), " backend. ",
              "Secrets are stored in environment variables")_

We need to prevent the code from reaching this line, in https://github.com/r-lib/keyring/blob/a1503f18de0cd1b1d44c4456e545b5e9f15a43dd/R/default_backend.R#L72 the default_backend_auto() function. 

This boils down to "keyring::backend_secret_service$new()$is_available()" being FALSE, which says the secret service daemon in my Linux is not running.

2. The alternative way is to investigate fundamentally how to set a the "R_KEYRING_KEYRING" environment variable, which stores the names of manually created keyrings. Stuck here though.

**Comment by robohyun66** [comment]
https://stackoverflow.com/questions/56522491/trouble-configuring-keyring-package-in-r-with-secret-service-api-in-linux Here someone is asking the same question as me.

**Comment by robohyun66** [comment]
From https://rdrr.io/cran/keyring/man/backend_secret_service.html

"See backend for the documentation of the individual methods. The is_available() method checks is a Secret Service daemon is running on the system, by trying to connect to it. It returns a logical scalar, or throws an error, depending on its argument:"

**Comment by robohyun66** [comment]
https://cran.rstudio.com/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

The "keyringr" package might be an alterntive.

**Comment by robohyun66** [comment]
I can check that *SOME* keyring daemon is running on my Linux (from
https://askubuntu.com/questions/898694/gnome-keyring-daemon-not-starting-up-properly)
`ps -ef | grep keyring`

Why can't my R's `keyring::backend_secret_service$new()$is_available()` find it
though?

**Comment by robohyun66** [comment]
@amishra-stats  Can you see if the original issue is a problem on your Mac as well? i.e. do you need to enter the API password every time you open a new R session?
