### ISSUE TITLE
Feature request : API key in Jupyter notebook

### ISSUE THREAD

**Issue by fribalet** [simonscmap/cmap4r#9]
Great package, thank you! I ran into a problem when I try to use the package in a Jupyter notebook. Unless I miss something, it looks like that the API key can only be set by a prompt (i.e `keyring::key_set()`). Would it be possible to add the API key without a prompt, like in `pycmap`? 
Thank you!

**Comment by amishra-stats** [comment]
Hi Francois,

Thank you for your query!

We have modified the "set_authorization" and "initialize_cmap" allowing a user to pass CMAP api key by value as implemented in pycmap.

Regards
Aditya

**Comment by fribalet** [comment]
Thank you Aditya for your swift response, that's perfect. 
Great package, really nice work!

Francois
